### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by mutonic** [kamranasif506/Educational-Symposium#2]
Overall, your project is impressive and well-implemented 💯 . You have followed the design guidelines effectively and have created a solid foundation. However, I have identified a couple of minor issues that can be addressed to improve the overall user experience.

1. Broken Logo in README:
The logo displayed in the README file appears to be broken. This can negatively impact the visual presentation of your project and may confuse users. I recommend fixing the issue by re-uploading the logo or updating the image source URL.

2. Remove "Add a link to your deployed project":
You have already deployed the project successfully, and it is evident from the provided documentation. Therefore, there is no need to include the instruction to "Add a link to your deployed project" in the README. Removing this instruction will avoid confusion and make the documentation more concise and precise.

Aside from these minor issues, I am thoroughly impressed with your work 🥇 . The project demonstrates strong coding practices, adheres to the design guidelines, and functions as intended. Keep up the great work and continue building upon this solid foundation.

**Comment by manzitresor** [comment]
Congratulations on the excellent design work! You've done a great job, and I want to commend you on your accomplishments. 🍾

### Review Highlights 🎯
👍 The design looks fantastic.
👍 No linter errors, indicating good code quality.
👍 Descriptive README, providing helpful information.

However, I agree with my colleague's suggestion that you could make a few changes to enhance the professionalism of your README.

Keep up the great work, and I'm confident that with these improvements, your project will shine even more!

**Comment by aradradev** [comment]
You did a good job. However,  there are some things I would like to suggest to you. Could you consider using one id attribute on your About page? Because the id value [program-heading] must be unique on each HTML. Good job 👍 💯
